version: '3.4'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "228:80"
      - "2288:443"
    environment:
      ASPNETCORE_URLS: https://+;http://+;
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: $ASPNETCORE_Password
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: $USERPROFILE\.aspnet\https
        target: /https/
      
